# Model arguments
model_name_or_path: meta-llama/Llama-3.2-3B-Instruct
ref_model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
torch_dtype: bfloat16
attn_implementation: sdpa
# LoRA arguments
use_peft: true
lora_r: 16
lora_alpha: 128
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj

# Data training arguments
dataset_mixer:
  data/reformatted/distill-deepSeek-R1-Distill-Llama-8B: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# DistiLLMTrainer arugments
bf16: true
do_eval: true
eval_steps: 10000000
gradient_accumulation_steps: 16
hub_model_id: llama
learning_rate: 5.0e-5
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
output_dir: ./outputs/llama-3.2-3B-it-nnm-chosen
run_name: llama-3.2-3B-it-nnm
per_device_train_batch_size: 1
per_device_eval_batch_size: 2
push_to_hub: false
# save_strategy: "steps"
# save_steps: 200
# save_total_limit: 20
save_strategy: "epoch"
save_total_limit: 5 
save_only_model: true
seed: 42
warmup_ratio: 0.1
loss_type: distillm_v2
save_safetensors: false


# NNM arguments — tên field phải khớp với trainer code
nnm_lambda: 0.05
nnm_K_centroids: 128
nnm_d_prime: 256
nnm_ns_iters: 5
nnm_warmup: 400
nnm_n_mid_layers: 4
nnm_chosen_weight: 1.0
nnm_rejected_weight: 1.0
nnm_centroid_batches: 3000
nnm_target: "chosen"   # "chosen" | "concatenated" | "both"
save_safetensors: false